#!/bin/bash

# vbdialog
#	main screen for vbdialog

pdir=`dirname $0`
pname=`basename $0`

source $pdir/vbfunctions.sh

# do we have an rc file?
dialogrc="$pdir/vbdialogrc"
[ -r "$dialogrc" ] && export DIALOGRC="$dialogrc"

#
#	default settings
#
export backtitle="Virtual Box"

#
#	provide the user with a list of available commands
#	NOTE: The command name should match the script name.
#
while :
do
	choice=`dialog --stdout --backtitle "$backtitle" --title "Main Menu" --default-item list \
		--menu "Select sub-menu, or <Cancel> to quit" 0 0 0 \
		createvm	"Create a new VM" \
		deletevm	"Delete a VM" \
		list		"List sub-menu" \
		modifyvm	"Modify VM sub-menu" \
		showvminfo	"Show VM Info sub-menu"`
	[ $? != 0 ] && break
	command="$pdir/vb-${choice}.sh"
	[ -x "$command" ] && $command
done

clear
echo "$pname: Terminated." >&2

