#!/bin/bash
#
# vbdialog
#	main screen for vbdialog
#
# Copyright (c) 2013 Fred Youhanaie
#	http://www.gnu.org/licenses/gpl-2.0.html
#

pdir=$(dirname $0)
pname=$(basename $0)

source $pdir/vbfunctions.sh

# do we have an rc file?
dialogrc="$pdir/vbdialogrc"
[ -r "$dialogrc" ] && export DIALOGRC="$dialogrc"

#
#	default settings
#
export backtitle="Virtual Box"

#
#	provide the user with a list of available commands
#	NOTE: The command name should match the script name.
#
while :
do
	choice=$(vbdlg 'Main Menu' --default-item list \
		--cancel-label 'Quit' \
		--menu "Select sub-menu, or <Cancel> to quit" 0 0 0 \
		createhd	"Create a new HD" \
		createvm	"Create a new VM" \
		deletevm	"Delete a VM" \
		list		"List sub-menu" \
		modifyvm	"Modify VM sub-menu" \
		showvminfo	"Show VM Info sub-menu" \
		stattach	"Storage Attachment sub-menu" \
		storagectl	"Storage Controller sub-menu")
	[ $? != 0 ] && break
	command="$pdir/vb-${choice}.sh"
	[ -x "$command" ] && $command
done

clearexit 0

