#!/bin/bash

# vbdialog
#	main screen for vbdialog

pdir=`dirname $0`
pname=`basename $0`

# do we have an rc file?
dialogrc="$pdir/vbdialogrc"
[ -r "$dialogrc" ] && export DIALOGRC="$dialogrc"

#
#	default settings
#
export backtitle="Virtual Box"

#
#	provide the user with a list of available commands
#	NOTE: The command name should match the script name.
#
while :
do
	exec 3>&1
	choice=`dialog --backtitle "$backtitle" --title "Main Menu" --default-item list \
		--menu "Select submenu, or <Cancel> to quit" 0 0 0 \
		list		"List submenu" \
		showvminfo	"Show VM Info submenu" \
		createvm	"Create a new VM" \
		2>&1 1>&3`
	retval=$?
	exec 3>&-
	[ "$retval" != 0 ] && break
	command="$pdir/vb-${choice}.sh"
	[ -x "$command" ] && $command
done

clear
echo "$pname: Terminated." >&2

